// ===============================================
// SexualSEO.jsx — Final High-Authority Version
// ===============================================

import React from "react";
import SEOWrapper from "./SEOWrapper";

export default function SexualSEO({ productUrls = [] }) {
  const jsonldData = [
    // ---------------------------------------------------
    // MAIN CATEGORY COLLECTION PAGE
    // ---------------------------------------------------
    {
      "@context": "https://schema.org",
      "@type": "CollectionPage",
      "name": "Sexual Wellness Products",
      "url": "https://healthyz.co/sexual",
      "description":
        "Shop sexual wellness essentials including condoms, lubricants, delay sprays, intimate wash, pregnancy kits, fertility aids and hygiene products with private and discreet delivery.",
      "isPartOf": {
        "@type": "WebSite",
        "name": "Healthyz",
        "url": "https://healthyz.co"
      }
    },

    // ---------------------------------------------------
    // PRODUCT GROUP SCHEMA (Big ranking signal)
    // ---------------------------------------------------
    {
      "@context": "https://schema.org",
      "@type": "ProductGroup",
      "name": "Sexual Wellness & Intimate Care",
      "url": "https://healthyz.co/sexual",
      "description":
        "Explore condoms, lubes, delay sprays, enhancers, pregnancy test kits, ovulation kits, period care, intimate wash, vaginal care and sexual health products for men and women.",
      "brand": {
        "@type": "Brand",
        "name": "Healthyz"
      }
    },

    // ---------------------------------------------------
    // DYNAMIC ITEM LIST (AUTOGENERATED FROM PRODUCTS)
    // ---------------------------------------------------
    {
      "@context": "https://schema.org",
      "@type": "ItemList",
      "name": "Sexual Wellness Product List",
      "itemListOrder": "https://schema.org/ItemListOrderAscending",
      "itemListElement": productUrls.map((url, index) => ({
        "@type": "ListItem",
        "position": index + 1,
        "url": url
      }))
    }
  ];

  return (
    <SEOWrapper
      title="Sexual Wellness Products – Condoms, Lubes, Delay Sprays & Intimate Care | Healthyz"
      description="Shop condoms, lubricants, delay sprays, intimate wash, pregnancy test kits, fertility aids, menstrual hygiene and performance enhancers at Healthyz. 100% private browsing and discreet delivery across India."
      keywords="sexual wellness, condoms online, lubricants, delay spray, intimate wash, pregnancy test kit, ovulation kit, performance enhancer, fertility products, sexual health products, private delivery, discreet shipping"
      canonical="https://healthyz.co/sexual"
      image="https://healthyz.co/og-image.png"
      jsonld={jsonldData}
    />
  );
}
